// Code generated by GoVPP binapi-generator. DO NOT EDIT.
//  source: /usr/share/vpp/api/tmc.api.json

/*
 Package tmc is a generated from VPP binary API module 'tmc'.

 It contains following objects:
	  2 messages
	  1 service

*/
package tmc

import "git.fd.io/govpp.git/api"
import "github.com/lunixbochs/struc"
import "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = struc.Pack
var _ = bytes.NewBuffer

/* Messages */

// TmcEnableDisable represents the VPP binary API message 'tmc_enable_disable'.
//
//            "tmc_enable_disable",
//            [
//                "u16",
//                "_vl_msg_id"
//            ],
//            [
//                "u32",
//                "client_index"
//            ],
//            [
//                "u32",
//                "context"
//            ],
//            [
//                "u8",
//                "is_enable"
//            ],
//            [
//                "u32",
//                "sw_if_index"
//            ],
//            [
//                "u16",
//                "mss"
//            ],
//            {
//                "crc": "0xa4617e49"
//            }
//
type TmcEnableDisable struct {
	IsEnable  uint8
	SwIfIndex uint32
	Mss       uint16
}

func (*TmcEnableDisable) GetMessageName() string {
	return "tmc_enable_disable"
}
func (*TmcEnableDisable) GetCrcString() string {
	return "a4617e49"
}
func (*TmcEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// TmcEnableDisableReply represents the VPP binary API message 'tmc_enable_disable_reply'.
//
//            "tmc_enable_disable_reply",
//            [
//                "u16",
//                "_vl_msg_id"
//            ],
//            [
//                "u32",
//                "context"
//            ],
//            [
//                "i32",
//                "retval"
//            ],
//            {
//                "crc": "0xe8d4e804"
//            }
//
type TmcEnableDisableReply struct {
	Retval int32
}

func (*TmcEnableDisableReply) GetMessageName() string {
	return "tmc_enable_disable_reply"
}
func (*TmcEnableDisableReply) GetCrcString() string {
	return "e8d4e804"
}
func (*TmcEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

/* Services */

type Services interface {
	TmcEnableDisable(*TmcEnableDisable) (*TmcEnableDisableReply, error)
}

func init() {
	api.RegisterMessage((*TmcEnableDisable)(nil), "tmc.TmcEnableDisable")
	api.RegisterMessage((*TmcEnableDisableReply)(nil), "tmc.TmcEnableDisableReply")
}
