// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tmc.proto

package tmc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// TmcConfig
type TmcConfig struct {
	ConfigName           string   `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	TcpMssClamping       uint32   `protobuf:"varint,2,opt,name=tcp_mss_clamping,json=tcpMssClamping,proto3" json:"tcp_mss_clamping,omitempty"`
	InterfaceName        string   `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	MssValue             uint32   `protobuf:"varint,4,opt,name=mss_value,json=mssValue,proto3" json:"mss_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TmcConfig) Reset()         { *m = TmcConfig{} }
func (m *TmcConfig) String() string { return proto.CompactTextString(m) }
func (*TmcConfig) ProtoMessage()    {}
func (*TmcConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_tmc_8ddfc6a13eb9328e, []int{0}
}
func (m *TmcConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TmcConfig.Unmarshal(m, b)
}
func (m *TmcConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TmcConfig.Marshal(b, m, deterministic)
}
func (dst *TmcConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TmcConfig.Merge(dst, src)
}
func (m *TmcConfig) XXX_Size() int {
	return xxx_messageInfo_TmcConfig.Size(m)
}
func (m *TmcConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TmcConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TmcConfig proto.InternalMessageInfo

func (m *TmcConfig) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *TmcConfig) GetTcpMssClamping() uint32 {
	if m != nil {
		return m.TcpMssClamping
	}
	return 0
}

func (m *TmcConfig) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *TmcConfig) GetMssValue() uint32 {
	if m != nil {
		return m.MssValue
	}
	return 0
}

func init() {
	proto.RegisterType((*TmcConfig)(nil), "tmc.TmcConfig")
}

func init() { proto.RegisterFile("tmc.proto", fileDescriptor_tmc_8ddfc6a13eb9328e) }

var fileDescriptor_tmc_8ddfc6a13eb9328e = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0xc9, 0x4d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc9, 0x4d, 0x56, 0x9a, 0xc5, 0xc8, 0xc5, 0x19,
	0x92, 0x9b, 0xec, 0x9c, 0x9f, 0x97, 0x96, 0x99, 0x2e, 0x24, 0xcf, 0xc5, 0x9d, 0x0c, 0x66, 0xc5,
	0xe7, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x41, 0x84, 0xfc, 0x12,
	0x73, 0x53, 0x85, 0x34, 0xb8, 0x04, 0x4a, 0x92, 0x0b, 0xe2, 0x73, 0x8b, 0x8b, 0xe3, 0x93, 0x73,
	0x12, 0x73, 0x0b, 0x32, 0xf3, 0xd2, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0xf8, 0x4a, 0x92,
	0x0b, 0x7c, 0x8b, 0x8b, 0x9d, 0xa1, 0xa2, 0x42, 0xaa, 0x5c, 0x7c, 0x99, 0x79, 0x25, 0xa9, 0x45,
	0x69, 0x89, 0xc9, 0xa9, 0x10, 0xd3, 0x98, 0xc1, 0xa6, 0xf1, 0xc2, 0x45, 0xc1, 0x06, 0x4a, 0x73,
	0x71, 0x82, 0x0c, 0x2b, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x01, 0x9b, 0xc4, 0x91, 0x5b, 0x5c,
	0x1c, 0x06, 0xe2, 0x27, 0xb1, 0x81, 0x1d, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x55, 0x08,
	0x72, 0x6c, 0xb5, 0x00, 0x00, 0x00,
}